{% set name = "axisregistry" %}
{% set version = "0.4.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/axisregistry-{{ version }}.tar.gz
  sha256: a75fe87265aaac22780b295181e9ff0d1d0b7aa7302310758c06ae25bc3cca06

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.2
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.7
    - protobuf >=3.19.4,<4
    - fonttools

test:
  imports:
    - axisregistry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googlefonts/axisregistry/
  summary: A python API to access data from the Google Fonts variable fonts axis registry.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
