{% set name = "axisregistry" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/axisregistry-{{ version }}.tar.gz
  sha256: 66ea474975959585e83cdd612a554b067485f9ce6d2d014b4b026443beb7c610

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm >=6.2
  run:
    - fonttools
    - protobuf ==3.19.4
    - python >=3.7

test:
  imports:
    - axisregistry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googlefonts/axisregistry/
  summary: A python API to access data from the Google Fonts variable fonts axis registry.
  license: Apache-2.0
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
