{% set name = "axisregistry" %}
{% set version = "0.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/axisregistry-{{ version }}.tar.gz
  sha256: 33fb839e9c869360a30cb8846dce0b1e8d153b6bef4a90f2b94e0696041b9c7a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm >=4,<6.1
  run:
    - fonttools
    - protobuf ==3.19.4
    - python >=3.7

test:
  imports:
    - axisregistry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googlefonts/axisregistry/
  summary: A python API to access data from the Google Fonts variable fonts axis registry.
  license: Apache-2.0
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
